### ISSUE TITLE
Integration into POSM

### ISSUE THREAD

**Issue by emilyhobson** [posm/posm-gcpi#14]
Per SOW: The resulting web interface will be deployable by individuals as well as being integrated with Portable OpenStreetMap (POSM)

**Comment by sconnelley** [comment]
Add GCPi tool as a Git submodule to [posm-local-home](https://github.com/posm/posm-local-home) repo.  The [nginx-deploy.sh](https://github.com/posm/posm-build/blob/master/kickstart/scripts/nginx-deploy.sh) in POSM will take of installing it.

Will probably need somesort of UI element in "posm-local-home" to link to app.

**Comment by emilyhobson** [comment]
There's a place in POSM to upload the GCPs into POSM we we'll have to identify
