### ISSUE TITLE
New use cases

### ISSUE THREAD

**Issue by emilyhobson** [posm/posm-gcpi#18]
https://github.com/OpenDroneMap/odm_data_copr/blob/master/gcp_list_noimg.txt
https://github.com/OpenDroneMap/odm_data_copr/blob/master/gcp_list_nocoord.txt

The noimg one is the priority.

Also, one (important) thing I forgot in the call: I can load a few images into the GCPi, but if I try e.g. https://github.com/OpenDroneMap/odm_data_toledo (an average size dataset), I crash the browser. If this is an easy fix, great. If not, please add to the proposed extension to address.

**Comment by emilyhobson** [comment]
gcp_list_noimg
memory improvements
gcp_list_nocoord

**Comment by ebrelsford** [comment]
Closing in favor of #27
