### ISSUE TITLE
Import GCP file in other projections

### ISSUE THREAD

**Issue by ebrelsford** [posm/posm-gcpi#20]
Should be specified on first line of imported file.

**Comment by ebrelsford** [comment]
Currently only supporting UTM and 4326, could potentially support others if we want to allow any proj.4 string--is that sufficient?

**Comment by dakotabenjamin** [comment]
We accept any proj4 string, however note that there are issues with angular coordinate systems.

**Comment by ebrelsford** [comment]
@dakotabenjamin Okay, I can add support for any proj4 string if that would be useful. I know [the ODM docs](https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap) say any GDAL-supported string is supported, but I'd prefer to stick with proj4 for this project if we can. We're using proj4js which only supports proj4 strings and a few EPSG codes.

**Comment by ebrelsford** [comment]
* [ ] Allow any proj4 string or UTM as currently implemented

**Comment by smathermather** [comment]
proj4 and UTM is good. Until someone waits gdal-js...
