### ISSUE TITLE
Show preview of GCP file when loading

### ISSUE THREAD

**Issue by ebrelsford** [posm/posm-gcpi#21]
Show first few lines, for reference

**Comment by ebrelsford** [comment]
Are we thinking this would be like the **export file** modal dialog?

![selection_002](https://user-images.githubusercontent.com/375002/35463717-0ec5cb36-02c0-11e8-86b6-bda620320884.png)

(But instead of **copy** and **save** your options are **cancel** and **open**?)

**Comment by smathermather** [comment]
That could work.

**Comment by smathermather** [comment]
It looks good. Can we have it auto expand to fit width (within reason)?

**Comment by ebrelsford** [comment]
Sure!
