### ISSUE TITLE
Add GCP id/name column

### ISSUE THREAD

**Issue by ebrelsford** [posm/posm-gcpi#26]
Should add ID label to map to show which GCP is associated with which.

Does this get exported in GCP file? Not seeing it in the [ODM documentation](https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap#running-odm-with-ground-control).

**Comment by dakotabenjamin** [comment]
This was a requested feature for GCPs but hasn't been implemented.

**Comment by smathermather** [comment]
This is more a requirement for tracking the GCPs in the GUI. There would be advantages if ODM also handled them so that errors could more accurately be calculated in the model, but this is not yet implemented in ODM.

**Comment by ebrelsford** [comment]
Got it, @smathermather, so we wouldn't export this data to a GCP file?

Could this be an auto-incrementing id (starting at 1) that we show when you hover overa  point? Or does it need to be more configurable?

**Comment by ebrelsford** [comment]
* [ ] Allow id/name column on import of GCP file--ids will usually be associated with known map coordinates
 * [ ] Display id/name on map points when available

**Comment by smathermather** [comment]
Lookin good.

**Comment by ebrelsford** [comment]
@smathermather this is implemented now with the [noimg](https://github.com/OpenDroneMap/odm_data_copr/blob/master/gcp_list_noimg.txt) format.

**Comment by smathermather** [comment]
Looks great!

**Comment by smathermather** [comment]
We should also be able to export IDs too (I prematurely closed this issue). If I import e.g. https://github.com/OpenDroneMap/odm_data_copr/blob/master/gcp_list_noimg.txt, we should export those IDs with the file as the last column.

This is the (newly changed) spec example:
https://github.com/OpenDroneMap/OpenDroneMap/pull/764/files#diff-46192065a3075a0beec5ebe9b52ae697

(Thanks for the tip @dakotabenjamin).

**Comment by ebrelsford** [comment]
@smathermather Sure that should be doable. Should we still allow input with [this format](https://github.com/OpenDroneMap/odm_data_copr/blob/master/gcp_list_noimg.txt)? The only format I'm seeing in the ODM test data is [this one](https://github.com/yjmenezes/OpenDroneMap/blob/1e6de26303fc657b39a4dc276a73d53375d4d992/tests/test_data/gcp_list.txt), which has the `idGCP` column at the end of each row.

**Comment by pierotofy** [comment]
I think the image field should always be required.

`<geo_x> <geo_y> <geo_z> <im_x> <im_y> <image_name>`

Optionally there could also be a label field after image_name:

`<geo_x> <geo_y> <geo_z> <im_x> <im_y> <image_name> [label]`

But I think we should stop here.

**Comment by smathermather** [comment]
@pierotofy — the use case for no image name and no image coordinates isn’t for ODM but for loading into GCPi, when the user has XYZ coordinates from gps or survey or otherwise but still needs to associate the GCP with the images and image positions using GCPi. The output from GCPi then is a complete GCP file.

**Comment by pierotofy** [comment]
@smathermather ah, that makes sense. All for it then.

@dakotabenjamin that would complicate things a bit on the parser side. Figuring out if the first column is a label or `geo_x` would need a header.

**Comment by ebrelsford** [comment]
Okay, I think that what we're doing here complies with what's going on in ODM. Just to recap:
 * In GCPi we accept [input like this one](https://github.com/OpenDroneMap/odm_data_copr/blob/master/gcp_list_noimg.txt) where there are no images, but the GCPs have labels
 * GCPi outputs [like this](https://github.com/yjmenezes/OpenDroneMap/blob/1e6de26303fc657b39a4dc276a73d53375d4d992/tests/test_data/gcp_list.txt), including labels if they exist at the end of the row, so it is still compatible with ODM

I believe this is how things work now and is deployed. @smathermather is there a nice way to test this from GCPi to ODM to confirm?

**Comment by smathermather** [comment]
I think that should work fine. For sure I can test, but first: @dakotabenjamin -- does the above referenced GCPi output work?
