### ISSUE TITLE
Cannot remove point from map

### ISSUE THREAD

**Issue by pierotofy** [posm/posm-gcpi#29]
Using Chrome 63, after adding a new point to the map, the leaflet popup that should allow a point to be deleted/locked cannot be pressed (it looks like it flickers, but click events are not being captured).

![image](https://user-images.githubusercontent.com/1951843/36077244-3351e07a-0f36-11e8-9526-305f20065863.png)

Seems to work fine on Firefox.

**Comment by pierotofy** [comment]
Just updated to latest `master`, looks this is still an issue. 

1. Click the "+" button.
2. Place GCP on map: popup appears, GCP is visible on map (and is orange)
3. Click the "Delete" link.
4. Nothing happens.

If you deselect the GCP, reselect it, then "Delete" link works.

Platform info: http://whatismybrowser.com/w/ACNMQ3F

**Comment by ebrelsford** [comment]
I can't reproduce this, having worked through your workflow multiple times with Chrome.

Can you please test on the deployed version rather than master to ensure we're talking about the same code?

If it's still an issue, can you see if there are any errors in the developer console?

**Comment by pierotofy** [comment]
Thanks for looking again, I've tested with the latest master and the issue is solved now.

It looks like it was solved with the changes in https://github.com/posm/posm-gcpi/commit/89abb976774549f55b4ce96a33560961aeac1146 as the last commit that has the issue is `63f4abcb`.

All good, then! This can be closed.
