### ISSUE TITLE
Find alternative to Mapzen for geolocation

### ISSUE THREAD

**Issue by pierotofy** [posm/posm-gcpi#31]
Unfortunately since Mapzen has shutdown, their APIs are not going to work anymore. The geolocation tool is going to be affected.

**Comment by smathermather** [comment]
Good catch. Guessing geocode.earth is an easy drop-in: https://mapzen.com/blog/v1-searching-for-the-road-ahead/

**Comment by ebrelsford** [comment]
Yes but it [costs $200/month](https://geocode.earth/#pricing).

**Comment by dakotabenjamin** [comment]
Are there any other, cheaper/free alternatives for low volume requests?

**Comment by smathermather** [comment]
If you apply for a preview, they do have a free level.

**Comment by dakotabenjamin** [comment]
Someone linked me to tilehosting.com

**Comment by ebrelsford** [comment]
Pretty sure the preview level for geocode.earth was only until the beginning of February, I'd probably lean toward using [Nominatim](https://nominatim.openstreetmap.org/).
