### ISSUE TITLE
Copy and Save buttons in export dialog are always disabled

### ISSUE THREAD

**Issue by pierotofy** [posm/posm-gcpi#32]
![image](https://user-images.githubusercontent.com/1951843/36077392-4c362f54-0f38-11e8-8d4c-63021e99dc4f.png)

Seems like the `valid` state variable in the ExportModal component is always undefined?

Sorry if this is part of a work in progress, I just noticed it and thought to report it.

**Comment by ebrelsford** [comment]
As the error message says, you don't have enough GCPs. Once you meet those requirements it works as expected.

**Comment by pierotofy** [comment]
Ahhh, totally missed the error message. It looked like a notice.😄 

May I suggest changing the font color of it to red?
