### ISSUE TITLE
Meaning of "lock" is confusing"

### ISSUE THREAD

**Issue by pierotofy** [posm/posm-gcpi#34]
Perhaps I've just misinterpreted what the purpose of the Lock function is, but if I add a point, press the "Lock" link from the popup of a point, I can still drag the point around?

**Comment by ebrelsford** [comment]
Lock just de-selects the point, I'm open to renaming it.

**Comment by smathermather** [comment]
Per @ebrelsford, this may be resolved once https://github.com/posm/posm-gcpi/issues/28 is built and tested.

**Comment by ebrelsford** [comment]
This will be covered in #28, closing as duplicate.
