### ISSUE TITLE
BUG: Random connections seem to get lost

### ISSUE THREAD

**Issue by dakotabenjamin** [posm/posm-gcpi#38]
Posting this for another user, so I don't have a first-hand account of the problems. Basically the user was going therough connecting locations to gcps, then went back to a photo he already did and noticed the connection to the map was missing. Then he checked and saw multiple photos were missing connections that he had made. Here's the data: https://github.com/OpenDroneMap/WestCreekPleasantValley

**Comment by ebrelsford** [comment]
@dakotabenjamin thanks for reporting this. Can you confirm that this is against the version on the Stamen studio?

If it was against that version my best guess is that the user wasn't "locking" the points that are created when you open an image. If you don't lock these, gcpi assumes you didn't actually want them and removes them.

I'm working on some UI improvements in #34 that should make that more clear (the points will remain yellow until you lock them, then turn green).

**Comment by ebrelsford** [comment]
I can't replicate this, closing unless we get steps to reproduce.
