### ISSUE TITLE
Uncaught exception when using EPSG codes

### ISSUE THREAD

**Issue by smathermather** [posm/posm-gcpi#39]
I think not supporting EPSG codes is a fine compromise, but when used, we get e.g. ```Uncaught EPSG:3753``` in the console, but no user message, and no ability to use the "Load" button.

To replicate, create a GCP file as follows:

```
EPSG:3753			
GCP01	2235498.309	687742.941	857.817
GCP02	2235375.538	687898.159	850.729
GCP03	2235316.44	687888.66	852.831
GCP04	2235448.914	687630.781	858.101
GCP05	2235411.479	687813.864	871.643
GCP06	2235202.193	687819.215	878.784
```

**Comment by ebrelsford** [comment]
Good catch, I'll work on this.

**Comment by ebrelsford** [comment]
I'll be deploying this soon, but here's what it looks like:

![selection_016](https://user-images.githubusercontent.com/375002/39204594-b62fb226-47e7-11e8-9773-3dee596fbf33.png)

**Comment by ebrelsford** [comment]
Deployed now, @smathermather close if you think it looks good?

**Comment by smathermather** [comment]
Looks great!
