### ISSUE TITLE
Help the user pick a projection

### ISSUE THREAD

**Issue by pierotofy** [posm/posm-gcpi#42]
I think this is confusing for many users. When you press the "Export File" button, after adding/linking the GCPs, the user is shown this window:

![image](https://user-images.githubusercontent.com/1951843/39663806-c8f4b600-5047-11e8-84af-aec27c5ee178.png)

It's not immediately clear that the user needs to type in a proj4 string. Perhaps this could be improved (a projection should be suggested based on the location of the points).

The `undefined` is also confusing.

Maybe this is a bug? I'm using latest Chrome on Linux. No error messages in the console.

**Comment by ebrelsford** [comment]
Yes this is a bug, it should be selecting a UTM based on the location of the points.

**Comment by pierotofy** [comment]
This is now fixed, thanks @ebrelsford!
