### ISSUE TITLE
Various Improvements / Feedback

### ISSUE THREAD

**Issue by pierotofy** [posm/posm-gcpi#5]
I've tested the interface, so far I've found these issues (tested on Chrome):
 - Dragging control points around the left panel, when zoomed in, makes them disappear as soon as they are dragged.
 - Dragging control points around the left panel, when zoomed out, does not align with the position of the pointer.
 - Once a point is added to the map, and a new point is being edited, the previous point cannot be interacted with (perhaps this is by design?).

Also these things perhaps could be improved from a user experience perspective:
 - Make left panel larger (at least 40% of screen), so that it's easier to navigate the images.
 - Avoid having to manually press the "Ground Control Point" link/button to add a new ground control point. Clicking on an image, where there is no existing GCP, should automatically add a new point.
 - Instead of having buttons on the left side panel to add/delete GCP, clicking on an existing GCP should bring up a dialog/popup (leaflet style) with options to delete/interact with the GCP.
 - Consider using left mouse button to add/drag around a new GCP, middle/right mouse click to delete a GCP. Dragging a GCP outside a picture/map could also be a way to remove a GCP.

**Comment by emilyhobson** [comment]
These are completed, correct?
