### ISSUE TITLE
transfer ownership?

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm-gcpi#52]
@pierotofy @ebrelsford 
is this repository the code used for the plugin that's currently part of WebODM?
would it make sense to transfer this repository to the opendronemap organization? we can also rename if you'd like, i'm not sure it's ever had a super-strong link to the POSM project and the overall POSM project is a bit stuck in the mud right now with an uncertain future.

**Comment by pierotofy** [comment]
Hey @danbjoseph :hand: we're open to host it under OpenDroneMap if you think it would help other users/devs discover it. I think the name rocks so I wouldn't change it (but @ebrelsford should probably decide on that). :+1: 

Edit: and yes

> is this repository the code used for the plugin that's currently part of WebODM?

**Comment by ebrelsford** [comment]
Sure I'm open to transferring it if it is a better fit in ODM. I don't have admin access so someone else would likely need to do that.

**Comment by danbjoseph** [comment]
i think it will help users discover it. done!
